version: '3.7'
services:
  fabric:
    container_name: fabric
    build:
      context: ./network
      dockerfile: Dockerfile
    volumes:
      - ./network:/etc/hyperledger/fabric
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7054:7054"
    command: ["sleep", "infinity"]

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - fabric

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend